stages:
  - build
  - deploy

# Build Docker image
build:
  stage: build
  script:
    - docker build -t kharmannn/ship-crawler:latest .
  only:
    - main
  tags:
    - crawler

# Run tests (or the Selenium script) inside the Docker container
deploy:
  stage: deploy
  script:
    - docker run --rm kharmannn/ship-crawler:latest python3 /app/src/abs_crawler.py
    - echo 'successfully run...'
  only:
    - main
  tags:
    - crawler